### ISSUE TITLE
Logic Errors in RetailPrivateSale.sol

### ISSUE THREAD

**Issue by IntelMin** [Datagen-Project/DataGen-Smart-Contracts#14]
[RetailPrivateSale.sol](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/main/contracts/RetailPrivateSale.sol)

1. Price is not correct
`uint256 public price = 7 * 10**5;` ([Line#28](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/main/contracts/RetailPrivateSale.sol#L28))
This line means that the price of 1 #DG is 7e-13 USDC. (1 #DG = 7 * 10**5 / 10**18 = 7e-13 USDC)

2. Discounting logic error
`if (balanceOfDG[msg.sender].add(amountDG) <= discountLimit)` [Line#83](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/main/contracts/RetailPrivateSale.sol#L83)
The left operand of this comparison expression should be `amountRaisedDG`.

3. Claim function error
`claimDataGen()` must have `afterClosed` modifier.
Otherwise, we can't calculate the sum of investment from a certain investor.
This sum will be used for min and max limits of investment from one investor.

4. Investment amount limit error
[Line#78](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/main/contracts/RetailPrivateSale.sol#L78)
Limits should be compare with `balanceOfDG[msg.sender] + amountDG`.
So the correct codes are as follows:
```
require(amountDG >= 10 * (10 ** 18), "Fund is less than 10,00 DGT");
require(balanceOfDG[msg.sender] + amountDG <= 10000 * (10 ** 18), "Fund is more than 10.000,00 DGT");
```

5. Withdraw DataGen error
`withdrawDataGen()` function is called by only owner.
However, in this case, we should leave the enough tokens so that investors can claim their purchased amounts.
In order to achieve it, we can add "uint256 claimedDG" variable to calculate the sum of claims.
And when withdrawing by owner, we should leave "amountRaisedDG - claimedDG" amount of tokens.

**Comment by viac92** [comment]
> 1. Price is not correct 
Correct the price [Line28](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/a9a863eb97cb500798fdcfac1ba895334fd4b9a8/contracts/RetailPrivateSale.sol#L28)

>2. Discounting logic error
Correct the left operand [Line93](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/a9a863eb97cb500798fdcfac1ba895334fd4b9a8/contracts/RetailPrivateSale.sol#L93)

>3. Claim function error
Add `afterClosed` modifier [Line127](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/a9a863eb97cb500798fdcfac1ba895334fd4b9a8/contracts/RetailPrivateSale.sol#L127)

>4. Investment amount limit error
Correct the logic [Line89](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/a9a863eb97cb500798fdcfac1ba895334fd4b9a8/contracts/RetailPrivateSale.sol#L89)

>5. Withdraw DataGen error
Correct the function add this line of code 
```
uint256 balanceMinusToClaim = balance - amountRaisedDG;
tokenReward.transfer(owner(), balanceMinusToClaim);
```
[Line145](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/a9a863eb97cb500798fdcfac1ba895334fd4b9a8/contracts/RetailPrivateSale.sol#L145)

I also modify the else logic at [Line96](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/a9a863eb97cb500798fdcfac1ba895334fd4b9a8/contracts/RetailPrivateSale.sol#L96) because we already check the accounts invest limit.

Please check this corrections.

**Comment by viac92** [comment]
These logical errors has been fixed.
